import type { Metadata } from "next";
import "./global.css";
import Providers from "./providers";
import React from "react";
import LayoutWrapper from "@/components/layoutWrapper";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Novel App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const userEncoded = cookieStore.get("x-user")?.value;

  // Decode Base64 nếu có
  const userFromServer = userEncoded
    ? Buffer.from(userEncoded, "base64").toString("utf-8")
    : undefined;

  console.log("User from server:", userFromServer);
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <Providers>
          <LayoutWrapper userFromServer={userFromServer}>
            {children}
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}